### ISSUE TITLE
TV

### ISSUE THREAD

**Issue by upintheairsheep** [ninakali/chip_scavenger#1]
Can you grab a screenshot of the Smart TV's operating system so I can determine the brand?

**Comment by ninakali** [comment]
I'm sorry, I am too lazy to do unpack the box with it now. :D Maybe later...

Judging by the lack of labels on the TV, and very similar TV being sold by Argos as super cheap TV under popular "Bush" brand, I'd say it is Bush.
<img width="771" alt="Screenshot 2023-02-03 at 18 59 40" src="https://user-images.githubusercontent.com/15848389/216685201-d1d08d71-ca1c-48b6-9dc8-a9d9f52b30d4.png">

But firmware actually has Toshiba UI, so it might have been Toshiba, too.
<img width="1297" alt="Screenshot 2023-02-03 at 18 52 07" src="https://user-images.githubusercontent.com/15848389/216683762-6f592fd3-89b2-40a3-a576-df1159ab8051.png">
<img width="1280" alt="Screenshot 2023-02-03 at 18 52 44" src="https://user-images.githubusercontent.com/15848389/216683891-1541799e-3558-4a27-88c0-8019f7c56144.png">

**Comment by upintheairsheep** [comment]
Can you also release a dump of the TV's firmware on the Internet Archive for reference purposes?

**Comment by upintheairsheep** [comment]
PLEASE???

**Comment by jeanthom** [comment]
how to get banned from a github issue 101

**Comment by ninakali** [comment]
@upintheairsheep  I'm afraid I cannot do so, but I guess _someone_ could. I wonder what reference purposes are you interested in? 

Google Search shows a few firmware bundles for this MB; if you're interested in sources, you should be able to request them from the TV manufacturer - it's running GPL code, you can sue them if they refuse.

**Comment by upintheairsheep** [comment]
Just upload it for the purpose of preservation on the internet archive, I want to just explore the TV firmware for fun and see if I can make some sort of software jailbreak.

**Comment by ninakali** [comment]
Sorry, can't do, unfortunately.
